#!/usr/bin/env node
/**
 * build-pages.mjs — builds the GitHub Pages site into ./site
 *
 * 1. Copies diagrams/ (interactive HTML + specs) into site/diagrams/
 * 2. Scans diagrams/json/*.architecture.json for diagram metadata
 * 3. Renders a static index.html grouping every diagram by category
 *
 * Zero dependencies. Run: node tools/build-pages.mjs
 */
import {
  readFileSync, writeFileSync, readdirSync, existsSync, mkdirSync, rmSync, cpSync,
} from 'node:fs';
import { join } from 'node:path';

const ROOT = process.cwd();
const SITE = join(ROOT, 'site');
const CATEGORIES = [
  { dir: 'system-design', label: 'System Designs', icon: '🏗️', blurb: 'End-to-end designs: feed ranking, delivery routing, leaderboards, search, ads, and more' },
  { dir: 'features',      label: 'Technology Guides', icon: '🧰', blurb: 'At-a-glance architecture of Redis, Kafka, PostgreSQL, Kubernetes, agentic AI, and the cloud' },
  { dir: 'concepts',      label: 'Core Concepts', icon: '🧠', blurb: 'Foundational patterns: caching, consistency, distribution' },
];

const esc = (s) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
const lc = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim();

// ── 1. clean output + copy diagrams ─────────────────────────────────────────
rmSync(SITE, { recursive: true, force: true });
mkdirSync(SITE, { recursive: true });
cpSync(join(ROOT, 'diagrams'), join(SITE, 'diagrams'), { recursive: true });

// ── 2. collect diagram metadata from specs ──────────────────────────────────
const specs = readdirSync(join(ROOT, 'diagrams', 'json')).filter((f) => f.endsWith('.architecture.json'));
const groups = new Map(CATEGORIES.map((c) => [c.dir, []]));
let unmapped = 0;

for (const file of specs) {
  const spec = JSON.parse(readFileSync(join(ROOT, 'diagrams', 'json', file), 'utf8'));
  const out = spec.meta?.output;
  if (!out) continue;
  const cat = CATEGORIES.find((c) => existsSync(join(ROOT, 'diagrams', c.dir, out)));
  if (!cat) { unmapped += 1; continue; }
  groups.get(cat.dir).push({
    title: spec.meta.title || file.replace('.architecture.json', ''),
    href: `diagrams/${cat.dir}/${out}`,
  });
}

for (const [, items] of groups) items.sort((a, b) => lc(a.title).localeCompare(lc(b.title)));
const total = [...groups.values()].reduce((n, g) => n + g.length, 0);

// ── 3. render index.html ────────────────────────────────────────────────────
const card = (d) => `        <a class="card" href="${d.href}">
          <h3>${esc(d.title)}</h3>
          <span class="open">Open diagram ↗</span>
        </a>`;

const sections = CATEGORIES.map((c) => {
  const items = groups.get(c.dir);
  if (!items.length) return '';
  return `    <section>
      <h2>${c.icon} ${c.label} <span class="count">${items.length}</span></h2>
      <p class="blurb">${esc(c.blurb)}</p>
      <div class="grid">
${items.map(card).join('\n')}
      </div>
    </section>`;
}).join('\n');

const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>System Design — Interactive Diagrams</title>
<style>
  :root { color-scheme: dark; }
  * { box-sizing: border-box; margin: 0; }
  body { font: 16px/1.6 system-ui, -apple-system, "Segoe UI", sans-serif; background: #0d1117; color: #e6edf3; }
  header { text-align: center; padding: 56px 16px 24px; }
  h1 { font-size: 2rem; letter-spacing: -.02em; }
  header p { color: #8b949e; margin-top: 8px; }
  header p b { color: #e6edf3; }
  main { max-width: 1080px; margin: 0 auto; padding: 16px 20px 64px; }
  section { margin-top: 40px; }
  h2 { font-size: 1.25rem; border-bottom: 1px solid #21262d; padding-bottom: 10px; }
  .count { color: #8b949e; font-weight: 400; font-size: .9rem; margin-left: 6px; }
  .blurb { color: #8b949e; font-size: .95rem; margin: 6px 0 16px; }
  .grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(310px, 1fr)); gap: 14px; }
  .card { display: block; background: #161b22; border: 1px solid #30363d; border-radius: 10px; padding: 16px 18px; text-decoration: none; color: inherit; transition: border-color .15s, transform .15s; }
  .card:hover { border-color: #58a6ff; transform: translateY(-2px); }
  .card h3 { font-size: .98rem; font-weight: 600; line-height: 1.4; }
  .card .open { display: inline-block; margin-top: 10px; font-size: .8rem; color: #58a6ff; }
  footer { text-align: center; color: #8b949e; font-size: .85rem; padding: 24px 16px 48px; }
  footer a { color: #58a6ff; text-decoration: none; }
</style>
</head>
<body>
<header>
  <h1>📚 System Design — Interactive Diagrams</h1>
  <p><b>${total}</b> interactive architecture diagrams · <a href="https://github.com/aishwary11/system-design" style="color:#58a6ff">source on GitHub ↗</a></p>
</header>
<main>
${sections}
</main>
<footer>Generated by <code>tools/build-pages.mjs</code> · hosted on GitHub Pages</footer>
</body>
</html>
`;

writeFileSync(join(SITE, 'index.html'), html);
console.log(`site: ${total} diagrams (${specs.length} specs, ${unmapped} unmapped) -> ${SITE}`);
for (const c of CATEGORIES) console.log(`  ${c.dir}: ${groups.get(c.dir).length}`);
